

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/page";
import { Provider } from "react-redux";
import { store } from "@/Store/store";
import Providers from "./_components/Providers/Providers";
import { Toaster } from "sonner";
import Footer from "./_components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Freshcart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>

      


           <Navbar></Navbar>
        {children}
        <Footer></Footer>
        
    

<Toaster
  position="top-right"
  richColors
  closeButton
  toastOptions={{
    duration: 4000,
    classNames: {
      toast:
        "group !bg-white !border !border-zinc-200 !text-zinc-900 !rounded-2xl !shadow-xl !px-4 !py-3",

      title: "!text-sm !font-semibold !text-zinc-900",

      description: "!text-xs !text-zinc-500",

      closeButton:
        "!bg-transparent !border-0 !text-zinc-400 hover:!text-zinc-700",

      success:
        "!bg-emerald-50 !border-emerald-400 !text-emerald-700 !shadow-emerald-500/10",

      error:
        "!bg-red-500 !border-red-500 !text-white !shadow-red-500/20",

      info:
        "!bg-blue-50 !border-blue-400 !text-blue-700 !shadow-blue-500/10",

      warning:
        "!bg-amber-50 !border-amber-400 !text-amber-700 !shadow-amber-500/10",
    },
  }}
/>
















      


        </Providers>


          
        
       
        
        
        </body>
    </html>
  );
}
